apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "permission-manager.serviceAccountName" . }}
  labels:
    {{- include "permission-manager.labels" . | nindent 4 }}
rules:
  # Allow discovery and checking of all resources to avoid escalation errors
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "bind", "escalate"]
  # Allow full management of RBAC resources
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  # Allow full management of core resources
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  # Allow full management of certificates
  - apiGroups: ["certificates.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  # Allow to create subjectaccessreviews for permission testing
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  # Support all other common groups for templates and internal CRDs
  - apiGroups: ["networking.k8s.io", "apps", "batch", "autoscaling", "gateway.networking.k8s.io", "permissionmanager.user"]
    resources: ["*"]
    verbs: ["*"]
