#!/bin/bash
set -e

echo "================================================================="
echo "🧹 Starting Complete Cleanup for Permission Manager..."
echo "================================================================="

echo "1. Deleting the 'permission-manager' namespace (This will remove the deployment, service, and secrets)..."
kubectl delete namespace permission-manager --ignore-not-found

echo "2. Deleting Custom Resource Definitions (CRDs)..."
kubectl delete crd permissionmanagerusers.permissionmanager.user --ignore-not-found
kubectl delete crd permissionmanagergroups.permissionmanager.user --ignore-not-found

echo "3. Deleting Template ClusterRoles (seeds)..."
kubectl delete clusterrole template-namespaced-resources___operation --ignore-not-found
kubectl delete clusterrole template-namespaced-resources___developer --ignore-not-found
kubectl delete clusterrole template-namespaced-resources___view --ignore-not-found
kubectl delete clusterrole template-cluster-resources___read-only --ignore-not-found
kubectl delete clusterrole template-cluster-resources___admin --ignore-not-found

echo "4. Deleting generated RBAC RoleBindings and ClusterRoleBindings..."
# Delete labeled bindings (generated by new versions)
kubectl delete rolebindings --all-namespaces -l generated_for_user --ignore-not-found
kubectl delete rolebindings --all-namespaces -l generated_for_group --ignore-not-found
kubectl delete clusterrolebindings -l generated_for_user --ignore-not-found
kubectl delete clusterrolebindings -l generated_for_group --ignore-not-found

echo "================================================================="
echo "✅ Cleanup successfully completed!"
echo "Note: Legacy bindings (created by older versions without labels) might still exist in your cluster."
echo "================================================================="
